"use client";

import { FormEvent, useEffect, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowDownRight, ArrowUpRight, Award, BriefcaseBusiness, Check, ChevronRight, Code2, Download, Github, GraduationCap, Linkedin, Mail, Menu, Moon, Send, Sparkles, Sun, X } from "lucide-react";

const links = ["About", "Experience", "Skills", "Projects", "Contact"];
const fade = { hidden: { opacity: 0, y: 24 }, visible: { opacity: 1, y: 0 } };

function Reveal({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return <motion.div className={className} initial="hidden" whileInView="visible" viewport={{ once: true, amount: 0.18 }} transition={{ duration: .55, ease: "easeOut" }} variants={fade}>{children}</motion.div>;
}

export default function Home() {
  const [dark, setDark] = useState(true); const [menu, setMenu] = useState(false); const [sent, setSent] = useState(false);
  useEffect(() => { document.documentElement.classList.toggle("dark", dark); }, [dark]);
  const scroll = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); setMenu(false); };
  const submit = (e: FormEvent) => { e.preventDefault(); setSent(true); };
  return <main>
    <div className="noise" />
    <nav className="nav"><button onClick={() => scroll("home")} className="brand">AS<span>.</span></button><div className="navlinks">{links.map(x => <button key={x} onClick={() => scroll(x.toLowerCase())}>{x}</button>)}</div><div className="navactions"><button aria-label="Toggle theme" className="icon-button" onClick={() => setDark(!dark)}>{dark ? <Sun size={17}/> : <Moon size={17}/>}</button><button className="outline small" onClick={() => scroll("contact")}>Let&apos;s talk <ArrowUpRight size={15}/></button><button className="mobile-menu icon-button" onClick={() => setMenu(!menu)}>{menu ? <X/> : <Menu/>}</button></div></nav>
    <AnimatePresence>{menu && <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }} exit={{ opacity: 0, height: 0 }} className="mobile-nav">{links.map(x => <button key={x} onClick={() => scroll(x.toLowerCase())}>{x}</button>)}</motion.div>}</AnimatePresence>
    <section id="home" className="hero wrap"><div className="orb orb-one"/><div className="orb orb-two"/><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .65 }} className="hero-copy"><p className="eyebrow"><Sparkles size={14}/> Available for quality-focused opportunities</p><h1>Building confidence<br/>into <em>every release.</em></h1><p className="intro">I&apos;m <b>Ankith S</b>, a Quality Engineer focused on reliable, scalable software through thoughtful automation, API validation, and agile collaboration.</p><div className="hero-actions"><button className="primary" onClick={() => scroll("projects")}>Explore my work <ArrowDownRight size={18}/></button><a className="outline" href="/Ankith-S-Resume.pdf" download>Download résumé <Download size={17}/></a></div></motion.div><motion.div initial={{ opacity: 0, scale: .94 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: .18, duration: .6 }} className="hero-card"><div className="card-top"><span>QA SYSTEM STATUS</span><i/><span>LIVE</span></div><div className="assurance"><span className="ring"><Check size={40}/></span><div><strong>Quality assured</strong><small>Test strategy · automation · collaboration</small></div></div><div className="terminal"><span>01</span><code>automate the repeatable</code><span>02</span><code>explore the unexpected</code><span>03</span><code>ship with confidence</code></div><div className="metrics"><div><b>4+</b><span>Years in QA</span></div><div><b>02</b><span>Enterprise projects</span></div><div><b>03</b><span>Certifications</span></div></div></motion.div></section>
    <section id="about" className="wrap section about"><Reveal><p className="eyebrow">01 / ABOUT</p><h2>Quality is more than<br/><em>finding defects.</em></h2></Reveal><Reveal className="about-copy"><p>Every successful release begins with confidence in quality. Over the past four years, I&apos;ve helped engineering teams deliver dependable applications by bringing together automation, exploratory testing, API validation, and close cross-functional collaboration.</p><p>I enjoy turning complex testing challenges into efficient, repeatable processes that strengthen both product quality and team productivity.</p><button className="text-link" onClick={() => scroll("experience")}>My career journey <ChevronRight size={17}/></button></Reveal></section>
    <section id="experience" className="wrap section"><Reveal><p className="eyebrow">02 / EXPERIENCE</p><h2>Experience shaped by<br/><em>delivery and detail.</em></h2></Reveal><div className="timeline"><Experience company="HashedIn by Deloitte" role="Quality Engineer 2" period="Current role" items={["Led quality activities for Agile product teams and collaborated with product stakeholders.","Built and maintained Selenium automation suites for reliable regression coverage.","Used root-cause analysis to strengthen release quality and reduce recurring defects.","Contributed to sprint planning, test strategy, and QA team coordination."]}/><Experience company="Unisys" role="Quality Assurance Engineer" period="Previous role" items={["Designed automation frameworks and supported functional and API testing.","Validated sprint releases, contributed to test strategy, and supported UAT readiness.","Performed peer reviews and partnered with delivery teams to improve test quality."]}/></div></section>
    <section id="skills" className="wrap section"><Reveal><p className="eyebrow">03 / TOOLKIT</p><h2>Tools for testing<br/><em>what matters.</em></h2></Reveal><div className="skills-grid">{[["Automation",["Selenium","TestNG","JUnit","Rest Assured"]],["Programming",["Java","SQL","Maven"]],["Quality Engineering",["Functional Testing","Regression Testing","Smoke Testing","Sanity Testing"]],["API & Performance",["API Testing","Postman","Performance Testing","Stress Testing"]],["Workflow",["Agile","Jira","Git","UAT Support"]]].map(([title, items], i) => <Reveal key={String(title)}><motion.div whileHover={{ y: -5 }} className="skill-card"><Code2 size={22}/><h3>{title}</h3><div>{(items as string[]).map(s => <span key={s}>{s}</span>)}</div><small>0{i + 1}</small></motion.div></Reveal>)}</div></section>
    <section id="projects" className="wrap section"><Reveal><p className="eyebrow">04 / SELECTED WORK</p><h2>Quality, in <em>context.</em></h2><p className="section-note">A selection of enterprise engagements reframed as focused case studies.</p></Reveal><div className="projects"><Project number="01" name="International Olympic Council" theme="Blue" tags={["Selenium Automation","Functional Testing","Regression Testing"]} challenge="Deliver reliable validation across a complex, high-visibility platform." approach="Combined automated regression coverage with thoughtful functional testing, root-cause analysis, and QA leadership." impact="Built confidence in release readiness through disciplined quality practices."/><Project number="02" name="Kroger Services" theme="Coral" tags={["Performance Validation","Stress Testing","Production Support"]} challenge="Help a service platform maintain readiness under demanding operating conditions." approach="Contributed functional testing, stress and performance validation, and cross-team production support." impact="Supported product readiness with a practical, end-to-end testing mindset."/></div></section>
    <section className="wrap section credentials"><Reveal><p className="eyebrow">05 / CREDENTIALS</p><h2>Always learning.<br/><em>Always improving.</em></h2></Reveal><div className="credential-grid"><Reveal><div className="cert"><Award/><div><small>CERTIFICATION</small><h3>Professional Scrum Master I</h3></div></div></Reveal><Reveal><div className="cert"><Award/><div><small>CERTIFICATION</small><h3>Certified Automation Tester</h3></div></div></Reveal><Reveal><div className="cert"><Award/><div><small>CERTIFICATION</small><h3>Certified Manual Tester</h3></div></div></Reveal><Reveal><div className="education"><GraduationCap/><div><small>EDUCATION</small><h3>B.Tech, Computer Science</h3><p>Gopalan College of Engineering & Management</p></div></div></Reveal></div></section>
    <section id="contact" className="wrap section contact"><Reveal><p className="eyebrow">06 / GET IN TOUCH</p><h2>Let&apos;s build better<br/><em>software together.</em></h2><p className="section-note">Have a quality challenge, role, or collaboration in mind? I&apos;d be glad to connect.</p></Reveal><Reveal><form onSubmit={submit} className="contact-form"><label>Your name<input required placeholder="What should I call you?"/></label><label>Email address<input required type="email" placeholder="you@company.com"/></label><label>Message<textarea required placeholder="Tell me a little about what you have in mind..." rows={4}/></label><button className="primary" type="submit">{sent ? <>Message received <Check size={18}/></> : <>Send message <Send size={17}/></>}</button>{sent && <p className="form-note">Thanks — this demo form is ready to connect to a form service before deployment.</p>}</form></Reveal></section>
    <footer className="wrap"><div><button className="brand" onClick={() => scroll("home")}>AS<span>.</span></button><p>Quality Engineer &amp; Automation Test Engineer</p></div><div className="socials"><a href="#contact" aria-label="Email"><Mail/></a><a href="#contact" aria-label="LinkedIn"><Linkedin/></a><a href="#contact" aria-label="GitHub"><Github/></a></div><small>© {new Date().getFullYear()} Ankith S. Crafted with care.</small></footer>
  </main>;
}

function Experience({ company, role, period, items }: { company: string; role: string; period: string; items: string[] }) { return <Reveal><article className="experience"><div className="experience-meta"><span>{period}</span><BriefcaseBusiness size={22}/></div><div><h3>{company}</h3><p className="role">{role}</p></div><ul>{items.map(i => <li key={i}>{i}</li>)}</ul></article></Reveal>; }
function Project({ number, name, theme, tags, challenge, approach, impact }: { number: string; name: string; theme: string; tags: string[]; challenge: string; approach: string; impact: string }) { return <Reveal><motion.article whileHover={{ y: -6 }} className={`project ${theme.toLowerCase()}`}><div className="project-header"><span>{number}</span><ArrowUpRight/><h3>{name}</h3></div><div className="tags">{tags.map(t => <span key={t}>{t}</span>)}</div><div className="case"><div><small>THE CHALLENGE</small><p>{challenge}</p></div><div><small>THE APPROACH</small><p>{approach}</p></div><div><small>THE OUTCOME</small><p>{impact}</p></div></div></motion.article></Reveal>; }
